addon/mixins/in-viewport.js
addon/utils/can-use-raf.js
addon/utils/check-scroll-direction.js
addon/utils/is-in-viewport.js
package.json
tests/acceptance/integration-test.js
tests/dummy/app/app.js
tests/dummy/app/components/foo-bar.js
tests/dummy/app/router.js
tests/helpers/resolver.js
tests/helpers/start-app.js
tests/unit/initializers/viewport-config-test.js
tests/unit/mixins/in-viewport-test.js
tests/unit/utils/check-scroll-direction-test.js
tests/unit/utils/is-in-viewport-test.js

Updates to pass rules.
Thanks @rwjblue and @brzpegasus! It was a very straightforward experience using `ember-suave`. :+1:

Install ember-suave to enforce DockYard styleguide.

---

addon/mixins/in-viewport.js

Fixed faulty deprecation warning logic.

---

.travis.yml
addon/mixins/in-viewport.js
bower.json
package.json

Removes deprecated scroll trigger.

Update ember-cli and dependencies

---

addon/mixins/in-viewport.js
package.json

Just in case of new Ember 2.3.0 Owner API.

Install ember-getowner-polyfill and replace this.container with getOwner(this)

---

addon/mixins/in-viewport.js

Use the element's innerHeight/Width

---

addon/mixins/in-viewport.js
addon/utils/is-in-viewport.js

Resolves offirgolan/ember-light-table#121

Use Ember.assign instead of Ember.merge if possible

---

.jscsrc

.jscsrc no longer used

---

app/initializers/viewport-config.js

jshint missing semicolon

---

app/initializers/viewport-config.js

Continues #74 to complete fix of https://github.com/offirgolan/ember-light-table/issues/121 (which probably should be re-opened).

Replace Ember.merge usage with Ember.assign when available

---

addon/mixins/in-viewport.js
package.json

Related https://github.com/rwjblue/ember-getowner-polyfill/pull/6

update ember-getowner-polyfill to remove deprecation

---

README.md

fix travis link

---

README.md
addon/mixins/in-viewport.js
tests/acceptance/integration-test.js
tests/dummy/app/controllers/infinity-scrollable-raf.js
tests/dummy/app/controllers/infinity.js
tests/dummy/app/styles/app.css
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/infinity-scrollable-raf.hbs
tests/dummy/app/templates/infinity-scrollable.hbs
tests/dummy/app/templates/infinity.hbs

Just some doc improvements.
Closes #129

Improve docs

---

addon/mixins/in-viewport.js

update rafLogic for scrollable area

---

.travis.yml
testem.js

Adds Firefox to the CI build.  Might be a good idea to ensure more than Chrome is working :trollface:

add firefox to travis

---

.eslintrc.js
.travis.yml
package-lock.json
package.json
tests/dummy/config/targets.js

upgrade to 3.1 ember

---

README.md

See jsfiddle here: https://jsfiddle.net/get0a4xr/15/

add note about didExitViewport and intersectionThreshold

---

.eslintignore
.eslintrc.js
package-lock.json
package.json

fix screaming security vulnerability 🔒

updates + fix w/ npm audit

---

README.md
tests/acceptance/infinity-test.js
tests/dummy/app/controllers/infinity-right-left.js
tests/dummy/app/router.js
tests/dummy/app/routes/infinity-right-left.js
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/infinity-right-left.hbs

right left scrolling example

---

addon/mixins/in-viewport.js
addon/services/-raf-admin.js
package-lock.json
package.json
tests/unit/mixins/in-viewport-test.js

Small TS lib that extracts common functionality for rAF.  https://github.com/snewcomer/raf-pool

Use rAFPool npm pkg

---

.travis.yml

https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Remove deprecated travis sudo:false flag

---

package-lock.json
package.json
tests/dummy/app/controllers/infinity-right-left.js
tests/dummy/app/controllers/infinity-scrollable-raf.js
tests/dummy/app/controllers/infinity-scrollable.js
tests/dummy/app/controllers/infinity.js
tests/dummy/app/routes/infinity-right-left.js
tests/dummy/app/routes/infinity-scrollable.js

Ensure dummy app runs in ie11

---

README.md
addon/initializers/viewport-config.js
addon/mixins/in-viewport.js

Small performance improvement to disable evt listeners on scroll.  Can make false in the future.

Add API to not listen to scroll direction

---

README.md
addon/-private/observer-admin.js
addon/-private/raf-admin.js
addon/mixins/in-viewport.js
addon/services/-observer-admin.js
addon/services/in-viewport.js
app/services/-observer-admin.js
app/services/-raf-admin.js
app/services/in-viewport.js
tests/unit/services/-observer-admin-test.js

Begin unwinding use of mixin to support modifiers

---

addon/mixins/in-viewport.js

No behaviour changes or bugs fixed.

rAF: small refactor to use new recursive function

---

package-lock.json
package.json

https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry

Pass IO Entry in callback

---

.travis.yml
addon/services/in-viewport.js
package-lock.json
package.json
tests/dummy/app/styles/app.css
tests/dummy/app/templates/infinity-right-left.hbs

This PR mainly removes the intersectionRatio check for exit
https://github.com/snewcomer/intersection-observer-admin/pull/6

Bump IO library to 0.2.2

---

addon/mixins/in-viewport.js

Fix didScroll

---

README.md

Add TOC (Table of Contents) for README.md to have better readability.

Update README.md with TOC

---

addon/-private/raf-admin.js
package-lock.json
package.json

https://github.com/snewcomer/raf-pool/pull/5

Update raf-pool 0.1.2

---

package-lock.json
package.json

Update deps and security vulns

---

package.json
yarn.lock

close #228 Best guess is their implementation is slightly different or perhaps not totally to spec.

Bump IntersectionObserverAdmin to support Cordova

---

addon/mixins/in-viewport.js

did this in the GH UI, so not 100% sure I got it right!

Upgrade debug message to deprecation

---

addon/services/in-viewport.js

https://api.emberjs.com/ember/release/functions/@ember%2Frunloop/scheduleOnce

ScheduleOnce is not deduping

---

README.md
addon/services/in-viewport.js
tests/acceptance/infinity-test.js
tests/dummy/app/components/dummy-artwork.js
tests/dummy/app/components/my-modifier.js
tests/dummy/app/controllers/infinity-built-in-modifiers.js
tests/dummy/app/templates/components/dummy-artwork.hbs
tests/dummy/app/templates/components/my-modifier.hbs
tests/dummy/app/templates/infinity-built-in-modifiers.hbs

[BUG]: Unable to use multiple {{in-viewport}} modifiers

---

.release-it.json
package.json
yarn.lock

Closes #223.
This introduces a basic automatic release flow which will create a new release on Github as well as publish it to npm and update the CHANGELOG.md. Ideally we should use the labels recommended here https://github.com/lerna/lerna-changelog#usage for a nice changelog og Github or we can also create our custom labels.
To be able to release this from the command line you should supply a github token for both release-it and lerna-changelog. Here's the docs:
https://github.com/release-it/release-it#github-releases
https://github.com/lerna/lerna-changelog#usage
The following command will start the release process `yarn run release`
PRs need to have one of these default labels as in the screenshot attached and they will have the icons as you can see by default. We can also create our …

Set up release-it and lerna-changelog

---

.travis.yml
addon/services/in-viewport.js
config/ember-try.js
ember-cli-build.js
package.json
tests/dummy/app/-config/index.js
tests/dummy/app/components/dummy-artwork.js
yarn.lock

https://medium.com/@kiwiupover/embroider-preparation-14d59edafc0b

[Deps]: Ember LTS && embroider test matrix

---

package.json
tests/dummy/app/components/my-class-raf.js
tests/dummy/app/components/my-class.js
tests/dummy/app/components/my-component.js
tests/dummy/app/controllers/infinity-class.js
tests/dummy/app/templates/components/my-class-raf.hbs
tests/dummy/app/templates/components/my-class.hbs
tests/dummy/app/templates/infinity-class.hbs
yarn.lock

close https://github.com/DockYard/ember-in-viewport/issues/254

Add Glimmer component for tests

---

.github/workflows/ci.yml
tests/dummy/app/components/dummy-artwork.js
tests/dummy/app/components/my-modifier.js
tests/dummy/app/templates/components/dummy-artwork.hbs
tests/dummy/app/templates/components/my-modifier.hbs
tests/dummy/app/templates/infinity-modifier.hbs

Also looking into https://discord.com/channels/480462759797063690/485447409296736276/785543624317468692

Improve dummy setup for dev/tests

---

package-lock.json
package.json

ref https://github.com/snewcomer/intersection-observer-admin/pull/31

[Test]: fix tests

---

package-lock.json
package.json

Closes # .
Allows the consuming app to use either version (v2 or v3) of ember-modifier.

Bump ember-modifier to v3 and allow either v2 or v3

---

CHANGELOG.md

Closes # .
help folks with upgrade and makes it simpler to understand what has changed

Add v4 changelog via lerna-changelog

---

addon/services/in-viewport.js
addon/utils/is-in-viewport.js

Replace Ember.assign usage with Object.assign
