DockYard/ember-in-viewport

README.md
addon/mixins/in-viewport.js

Closes #1 
This commit allows each Ember.Object that the Mixin is extended with to
register their own instance of event listeners on the window and/or
document. This means `viewportSpy` will now work when the run loop fall
back is active.

Listeners are now registered and removed based on elementId

---

addon/mixins/in-viewport.js

Closes #2 
This commit enables `viewportSpy: false` to work when rAF is enabled.
The Mixin essentially stores an object with elementIds as keys for all Objects
with the Mixin, and with their respective requestAnimationFrame ids as
values. This allows for `#_unbindListeners` to cancel the appropriate
animation frame, based on that Component's elementId.

Register the Component's elementId along with it's rAF call

---

app/mixins/in-viewport.js
app/utils/can-use-dom.js
app/utils/can-use-raf.js
app/utils/is-in-viewport.js
tests/unit/mixins/in-viewport-test.js
tests/unit/utils/is-in-viewport-test.js

This commit removes the mixins and utils directories from the app tree,
as we should prefer importing directly from ember-in-viewport as opposed
to being relative to their app.
- Closes #5. Thanks to @rwjblue for reporting this

Don't re-export mixins/utils in app tree

---

README.md
addon/mixins/in-viewport.js

Closes #7. This commit is a general refactor of the Mixin for performance improvements. The Mixin now fires actual 'hooks', named `didEnterViewport` and `didExitViewport`, which you can use in your app in place of observers. For example,
```js
export default Ember.Component.extend(InViewportMixin, {
handleDidEnterViewport: on('didEnterViewport', function() {
console.log('entered');
}),
handleDidExitViewport: on('didExitViewport', function() {
console.log('exited');
})
});
```
Full changelog:
- refactored `_setViewportEntered`
- now triggers Events
- removed unnecessary Ember.warn
- updated debounce method to use fat arrow
- explicitly set `viewportEntered` when removing viewportSpy to prevent race conditions setting it to false
- renamed `_viewportDidEnter` to `_unbindIfEntered` which is …

General refactor, fire Evented hooks

---

README.md
addon/mixins/in-viewport.js
addon/utils/can-use-raf.js
addon/utils/check-scroll-direction.js
addon/utils/is-in-viewport.js
tests/unit/utils/check-scroll-direction-test.js

First pass at getting hooks setup for a waypoints implementation. The goal is to replace the third party `waypoints` library used in `ember-waypoints` with an ember-addon. It isn't very optimized yet, but functionally ready.
Addresses #9.

Initial implementation of waypoints

---

addon/mixins/in-viewport.js

Without this guard my tests were failing as `element` was `null` some times. most likely because it was already removed from dem DOM because I destroyed the App in the afterEach-hook of a test.

Guard against removed element

---

README.md
addon/mixins/in-viewport.js
app/initializers/viewport-config.js
config/environment.js
tests/unit/initializers/viewport-config-test.js

This commit adds an initializer that extracts a `viewportConfig` object
from `config/environment`, then makes it available in the container as
'config:in-viewport'. This allows the user to pass in their own global
defaults inside `config/environment`. 
Other changes: `direction` is now passed to the `didScroll{...}` 
triggers.
Closes #10.

Added the ability to pass in application wide defaults.

---

addon/mixins/in-viewport.js

This prevents an issue where `viewportEntered` would be `false` when
`didEnterViewport` fires, and vice versa.
Closes #16

Set `viewportEntered` before triggering the `didEnterViewport` hook.

---

app/initializers/viewport-config.js

Prevents an error when `viewportConfig` is not defined in the app's
config.
Closes #15.

Set default value for `viewportConfig`.

---

app/initializers/viewport-config.js
config/environment.js

This prevents an issue where a consuming app's config would not be
deeply merged with the default config, which would make some props
undefined.
Closes #19.

Move default config to initializer.

---

README.md
addon/mixins/in-viewport.js

- Also cleaned up some formatting.

Deprecated `didScroll{Up,Down,Left,Right}` in favour of `didScroll(...)`

---

addon/mixins/in-viewport.js
tests/unit/utils/check-scroll-direction-test.js

Ember 2.0 has removed EnumerableUtils causing ember-in-viewport to fail

Remove EnumerableUtils for Ember 2.0

---

addon/mixins/in-viewport.js
addon/utils/check-scroll-direction.js
app/initializers/viewport-config.js

This commit fixes a deprecation warning in Ember 2.x where initializers
no longer receive the container as an argument. The fix is backwards
compatible.
It also fixes an issue where default listeners would not be applied
correctly.

Fix deprecation warning and faulty defaults

---

addon/mixins/in-viewport.js

When scrolling through a large list of components with the InViewport mixin, the `_triggerDidAccessViewport` method can set the `viewportEntered` property to false after listeners for the component have been unbound, causing the components to remain stuck in their outside viewport state. `viewportEntered` should only be set back to false if the spy is being used.

Prevent unsetting viewportEntered when not spying

---

addon/mixins/in-viewport.js

Guard against `viewportListeners` being undefined

---

app/initializers/viewport-config.js

Only listen to `touchmove.scrollable` with the `document` context if a DOM is present.  This currently breaks with FastBoot.

BUGFIX: only attach to touchmove.scrollable event if DOM is present, fixes FastBoot integration

---

README.md
addon/mixins/in-viewport.js
app/initializers/viewport-config.js
tests/acceptance/integration-test.js
tests/dummy/app/components/my-component.js
tests/dummy/app/templates/index.hbs

allow disabled viewport listening

---

addon/utils/is-in-viewport.js
tests/unit/utils/is-in-viewport-test.js

Rounds the dimensions on the DOMRect of the in-viewport element since
`jQuery.innerWidth()` (or `height`) return integers.
`Element.getBoundingClientRect()` can return subpixels (as floating
point numbers) that if not handled will result in elements not being
considered in the viewport by the `is-in-viewport` helper (even though
they are).
This is particularly important when the user has zoomed the window,
in which case the browser may scale the size of the viewport, resulting
in the dimensions having fractional parts, e.g., the width might be
`1451.1112060546875`.
Closes #96
Rounds the `right` and `bottom` properties on the `DOMRect` returned from `Element.getBoundingClientRect()` on the element being checked to integers.
I have tested by `npm link`ing this change against [this …

bug: handle subpixel values in viewport dims

---

addon/utils/is-in-viewport.js

The `assign` was overwriting the default tolerances, making all in viewport tests assume them.

don't overwrite default defaultTolerance

---

README.md

While reading through the README, I noticed there wasn't an installation section. So I'm just adding an installation header with the command used to install this on another project.
- Adds an installation header with a code snippet to run `ember install ember-in-viewport`

Adds installation section

---

tests/acceptance/integration-test.js

scrolling the window did not actually bring the element into the viewport.
the test container needed to be scrolled
This PR fixes the build by fixing a test that is currently failing.

fixes test/build

---

README.md
addon/mixins/in-viewport.js
addon/utils/can-use-intersection-observer.js
addon/utils/check-scroll-direction.js
addon/utils/is-in-viewport.js
app/initializers/viewport-config.js
package-lock.json
package.json
tests/acceptance/infinity-test.js
tests/acceptance/integration-test.js
tests/dummy/app/components/my-component.js
tests/dummy/app/controllers/infinity-scrollable-raf.js
tests/dummy/app/controllers/infinity-scrollable-scrollevent.js
tests/dummy/app/controllers/infinity-scrollable.js
tests/dummy/app/controllers/infinity.js
tests/dummy/app/router.js
tests/dummy/app/routes/infinity-scrollable-raf.js
tests/dummy/app/routes/infinity-scrollable-scrollevent.js
tests/dummy/app/routes/infinity-scrollable.js
tests/dummy/app/routes/infinity.js
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/infinity-scrollable-raf.hbs
tests/dummy/app/templates/infinity-scrollable-scrollevent.hbs
tests/dummy/app/templates/infinity-scrollable.hbs
tests/dummy/app/templates/infinity.hbs
tests/unit/initializers/viewport-config-test.js

This PR provides an easy upgrade path to use IntersectionObserver.  This also doesn't have any effect on existing users and will fallback to rAF if not in target browser.
Also added two routes - `infinity` and `infinity-scrollable` to perf-test and test.
close #106 #67 
Ref prev PR #112 
Partial Fix #37

Use IntersectionObserver if available

---

addon/mixins/in-viewport.js
tests/dummy/app/components/my-component.js
tests/dummy/app/controllers/infinity-scrollable.js
tests/dummy/app/templates/infinity-scrollable.hbs
tests/integration/components/my-component-test.js

@bkoval This is completely my fault.  I didn't have a test for the `viewportTolerance`.  
This is a small fix, but in reality there still are a few things we can still improve - better tests for viewportTolerance and intersectionThreshold, allow % for viewportTolerance in the IntersectionObserver case, etc.  I'll make a follow up issue.
References #121

Fix viewportTolerance with defaults

---

README.md
addon/initializers/viewport-config.js

To be inline with the IntersectionObserver spec, I think we should make the `threshold` value default to 0, meaning the `didEnterViewport` will trigger when the first pixel of the `target` has entered the scrollable area.

change intersection threshold default to 0

---

addon/mixins/in-viewport.js
tests/acceptance/infinity-test.js
tests/acceptance/integration-test.js
tests/dummy/app/controllers/infinity-scrollable-raf.js
tests/dummy/app/styles/app.css
tests/dummy/app/templates/infinity-scrollable-raf.hbs

Add a test for rAF scrollable area that is offset from top of browser window.
Also added `false` to the `scrollIntoView` methods.  This aligns the bottom of the element to the bottom of the visible part of the scrollable ancestor.  Previously, we were aligning the top of the element with the top of the visible area (the default)

Raf test bounding

---

addon/mixins/in-viewport.js

Closes #42 
When looking into performance issues with our app we discovered that the `requestAnimationFrame` approach is really noisy on the main thread.  We noticed after all images had been lazy loaded it was still ticking away requesting animation frames indefinitely.  We want to cancel the previous request before losing track of the current request id. 
~2 seconds of recorded performance:
Each of these is a call to `_setViewportEntered`, one for each lazy image on the screen. Called 60fps waiting for an element to enter the screen.
Once all images have been loaded, the main thread is now quiet.

Cancel animation frame before requesting again

---

README.md
addon/mixins/in-viewport.js

Closes #146 
If the user sets `viewportUseIntersectionObserver`, we will override it with our internal check to see if the mixin can support Intersection Observer.

Ensure explicitly setting viewportUseIntersectionObserver is not allowed

---

README.md
addon/mixins/in-viewport.js
addon/services/-observer-admin.js
addon/services/-raf-admin.js
app/services/-in-viewport.js
app/services/-observer-admin.js
app/services/-raf-admin.js
tests/unit/mixins/in-viewport-test.js

This PR aims to use a service that utilizes IntersectionObserver's ability to observe multiple elements.  Currently, we are instantiating a new IntersectionObserver per element on page.  However, one optimization, especially in cases where many elements are beings watched (think advertisements or lazy loading hundreds of pictures), is simply use the same IntersectionObserver to watch multiple entries.
close #119

 Use one IntersectionObserver per viewport

---

addon/mixins/in-viewport.js
addon/services/-observer-admin.js
tests/unit/services/-observer-admin-test.js

The root scrollable area can have multiple elements with different observer options.  To prevent the first element's options from overriding the rest of the observers in the static administrator (cache to reuse intersection observer instances), we need to ensure that when we want to find a potential match for an element, that we compare the to be added element's observer options and only reuse the instance of the IntersectionObserver iff the element shares the same root and same observer options

Allow `root` on static admin to have multiple keys

---

addon/mixins/in-viewport.js
addon/services/-raf-admin.js

If there are many elements on the page, rAF `cancel` effects other observed elements.  This was just a minor optimization but the downsides of this outweigh those benefits.
Reverting for now but need to revisit.
Ref #145 #152 
close #154

 Do not cancel rAF as this effects other elements that are observed

---

addon/mixins/in-viewport.js
addon/services/-observer-admin.js
tests/unit/services/-observer-admin-test.js

@kevinansfield - looks like this is a serious error so cherry picked your commit (I also have it).  It's a little verbose (extra function params), but lmk if you have time to review.  I'll update ember-infinity if we are ok with this!
Ref #161 
close #161

Handle root with gaining sizzle properties 

---

addon/services/-observer-admin.js

I'm seeing some memory leaks due to retained object in our intersection observer administrator.
The use of `window` as a key is causing memory to be retained between each test run.

Fix scope memory leak

---

addon/utils/is-in-viewport.js
tests/unit/utils/is-in-viewport-test.js

Right now, the w and height of the sentinel are not taken into account when determining if it is in viewport or not.  As a result, it only triggers the relevant actions when the whole element is in viewport.

Ensure rAF takes into account sentinels w and h

---

.gitignore
.npmignore
.travis.yml
addon/mixins/in-viewport.js
addon/services/-observer-admin.js
config/ember-try.js
package-lock.json
package.json

Another PR to follow that consolidates the mixin logic somewhere and a pool to maintain watched element + it's options ) + it's observer so it can be shared across boundaries (mixin or modifier)
Ref #177

 Update 3.8 and prep for modifiers

---

README.md
addon/mixins/in-viewport.js
package-lock.json
package.json
tests/dummy/app/components/my-modifier.js
tests/dummy/app/controllers/infinity-modifier.js
tests/dummy/app/router.js
tests/dummy/app/routes/infinity-modifier.js
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/components/my-modifier.hbs
tests/dummy/app/templates/infinity-modifier.hbs

This is not the final product, but the start of how one could use a modifier inside a component. 
No feature added.  Required a slight refactor to the mixin but seems like the easiest path for now if people want to use an element modifier inside a component (w/ or w/o a tagName btw!)
In the example in the dummy app, it uses `did-insert` from [@ember/render-modifiers](https://github.com/emberjs/ember-render-modifiers) and adds the specific element to the pool of elements that we watch.  
You could possibly use this to watch multiple nodes.
```js
export default Component.extend(InViewportMixin, {
didInsertHeader() {}
didInsertFooter() {}
didInsertHeroImage() {}
});
```
although for this to work with multiple items, we would need to figure out what to do when triggering `didEnterViewport` …

Just a small town boy living in a ember modifier world

---

addon/-private/observer-admin.js
addon/mixins/in-viewport.js
addon/services/in-viewport.js
package-lock.json
package.json
tests/unit/services/-observer-admin-test.js

This update adds the ability register callbacks with intersection observer admin.  Eventually will try to return outan instance and allow end user to add the callback function.
https://github.com/snewcomer/intersection-observer-admin/pull/5

Internal: Update IntersectionObserverAdmin + simplify

---

.eslintrc.js
README.md
addon/-private/observer-admin.js
addon/-private/raf-admin.js
addon/mixins/in-viewport.js
addon/services/in-viewport.js
package-lock.json
package.json
tests/.eslintrc.js
tests/acceptance/infinity-test.js
tests/dummy/app/components/my-class-raf.js
tests/dummy/app/components/my-class.js
tests/dummy/app/controllers/infinity-class.js
tests/dummy/app/router.js
tests/dummy/app/routes/infinity-class.js
tests/dummy/app/styles/app.css
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/components/my-class-raf.hbs
tests/dummy/app/templates/components/my-class.hbs
tests/dummy/app/templates/infinity-class.hbs
tests/dummy/app/templates/infinity-scrollable-raf.hbs

@gossi 👋 again!  This PR adds the ability to use classes if your target browser supports IntersectionObserver (e.g. not Safari).  I likely won't merge this until we can at least support rAF, but wanted to get your feedback first.  Thoughts on naming?
This PR adds three user facing APIs.
- `watchElement`
- `addEnterCallback`
- `addExitCallback`
```js
import Component from '@ember/component';
import { tagName } from '@ember-decorators/component';
import { inject as service } from '@ember/service'; // with polyfill
@tagName('')
export default class MyClass extends Component {
@service inViewport
didInsertElement() {
const loader = document.getElementById('loader');
const { didEnter } = this.inViewport.watchElement(loader);
didEnter(this.didEnterViewport.bind(this));
}
didEnterViewport() { …
```

New API: watchElement for classes with no mixin

---

addon/mixins/in-viewport.js

It was recently happening to me on my acceptance test and failed them.
`if (!isTearingDown && viewportSpy || viewportEntered)` line evaulated wrongly because of         
`const viewportEntered = element.getAttribute('data-in-viewport-entered');` retrieve the boolean value in string.
When `isTearingDown` is `true` whole expression in the `if` (`!isTearingDown && viewportSpy || viewportEntered`) evaluated string `"true"` and casted non-empty string true.
So I cast the string boolean value properly in this PR.

Fixing if condition with casting proper boolean

---

addon/mixins/in-viewport.js

Closes #216 
The `in-viewport` service has a `startIntersectionObserver` function which creates an instance of `observerAdmin`. The `in-viewport` mixin has a call to `startIntersectionObserver` that does not check to see if `observerAdmin` already exists. This resulted in the single instance of `observerAdmin` inside the service being replaced every time a component using the mixin was created. `observerAdmin` has `WeakMap` "registry"s of `element` references that are useful to have access to when debugging issues using this addon, and the instance changing made that impossible to leverage.
The mixin's call to `startIntersectionObserver` proves to be unnecessary as it is immediately called inside `watchElement`. That call IS protected so that `observerAdmin` is only ever created once. …

fixes #216, remove unnecessary call to startIntersectionObserver

---

README.md
addon/services/in-viewport.js
tests/acceptance/infinity-test.js
tests/acceptance/integration-test.js
tests/dummy/app/components/dummy-artwork.js
tests/dummy/app/controllers/infinity-built-in-modifiers.js
tests/dummy/app/controllers/infinity-modifier.js
tests/dummy/app/templates/components/dummy-artwork.hbs
tests/dummy/app/templates/infinity-built-in-modifiers.hbs

Built in modifier test and README

---

.eslintrc.js
README.md
tests/acceptance/infinity-test.js
tests/dummy/app/components/dummy-artwork.js
tests/dummy/app/templates/components/dummy-artwork.hbs
tests/dummy/app/templates/infinity-built-in-modifiers.hbs
tests/dummy/app/templates/infinity-modifier.hbs

- Some updated examples with classes
- Stop suggesting Mixin as first approach.

Improve docs

---

addon/-private/raf-admin.js
addon/services/in-viewport.js
tests/acceptance/infinity-test.js
tests/dummy/app/components/dummy-artwork.js
tests/dummy/app/controllers/infinity-built-in-modifiers.js

Noticed that callbacks registered with the `in-viewport` element modifier were never being fired when the browser falls back to rAF-based detection. It seems that the enter and exit callbacks were always being set to noops when setting up elements to be watched.
Also found that the test controller was leaking the model state between tests, so fixed that up as well.
Thanks for the great addon! ❤️

Fixing in-viewport element modifier with rAF-based detection

---

addon/services/in-viewport.js

Put the service teardown code in willDestroy() instead of destroy() so it runs at the expected time. destroy() schedules a call to willDestroy() on the run loop, so they happen at different times, and willDestroy() is the hook where teardown code is expected to live. Starting in Ember 3.20 having this code in destroy() can cause test teardown bugs if a modifier calls into the service to stop watching, because things happen in this order:
1. Service's destroy() method is called (by the container)
2. Modifiers' willRemove() hooks are called
3. Service's willDestroy() hook is called
So the service's teardown code needs to live in willDestroy() or else it will have already torn down by step (2) and calls into it from modifier teardown code can cause errors.
Note that I did not add any new …

Fix test failures in Ember 3.20: Run service teardown code in willDestroy()

---

package.json
yarn.lock

https://github.com/snewcomer/intersection-observer-admin/commit/aabb5790955b31dc7a0ae0f6e8d5e0ba408e5ea6
hasOwnProperty() should never be called from the object but from the generic prototype like is done in the commit above.

Intersection-Observer-Admin 0.2.13

---

README.md
addon/-private/raf-admin.js
addon/services/in-viewport.js

This is similar to #210 except that #210 targeted browser *with* `IntersectionObserver` support and this PR fixes the same issue for the browsers that do not have `IntersectionObserver` support and rely on RAF admin.

Support scrollableArea as an element

---

README.md
addon/modifiers/in-viewport.js
tests/acceptance/infinity-test.js
tests/dummy/app/components/my-modifier.js
tests/dummy/app/controllers/infinity-built-in-modifiers.js
tests/dummy/app/controllers/infinity-modifier.js
tests/dummy/app/templates/infinity-built-in-modifiers.hbs
tests/dummy/app/templates/infinity-modifier.hbs
tests/integration/components/my-component-test.js

Bug: stop watching unless viewportSpy=true is passed to modifier

---

package-lock.json
package.json

The fixes in the underlying library were due to test issues.  Unsure of the exact cause so far.  Reverting to give myself more time to investigate.
close https://github.com/snewcomer/intersection-observer-admin/issues/30
ref #271

[Bug]: revert intersection-observer-admin bug with multiple elements sharing a single root

---

addon/initializers/viewport-config.js

Ember.assign is deprecated in Ember 4.x.
Closes #298

Replace assign polyfill with Object.assign
